'''
Universidad de La Laguna
Máster en Ingeniería Informática
Trabajo de Final de Máster
Pyimagos development

Contour operation that modifies a given contours array generated by
cv.findContour()
'''

from abc import ABC, abstractmethod

class ContourOperation(ABC):
  @abstractmethod
  def generate_new_contour(self, contours: list) -> list:
    pass
    
